/* eslint-disable @typescript-eslint/no-redeclare */

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export type LOGIN_REQUEST = typeof LOGIN_REQUEST
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS
export const LOGIN_FAILED = 'LOGIN_FAILED'
export type LOGIN_FAILED = typeof LOGIN_FAILED

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export type REGISTER_REQUEST = typeof REGISTER_REQUEST
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export type REGISTER_SUCCESS = typeof REGISTER_SUCCESS
export const REGISTER_FAILED = 'REGISTER_FAILED'
export type REGISTER_FAILED = typeof REGISTER_FAILED

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export type GET_USER_REQUEST = typeof GET_USER_REQUEST
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export type GET_USER_SUCCESS = typeof GET_USER_SUCCESS
export const GET_USER_FAILED = 'GET_USER_FAILED'
export type GET_USER_FAILED = typeof GET_USER_FAILED

export const CLEAN_USER = 'CLEAN_USER'
export type CLEAN_USER = typeof CLEAN_USER

export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST'
export type GET_CLASSES_REQUEST = typeof GET_CLASSES_REQUEST
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS'
export type GET_CLASSES_SUCCESS = typeof GET_CLASSES_SUCCESS
export const GET_CLASSES_FAILED = 'GET_CLASSES_FAILED'
export type GET_CLASSES_FAILED = typeof GET_CLASSES_FAILED

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST'
export type CREATE_CLASS_REQUEST = typeof CREATE_CLASS_REQUEST
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS'
export type CREATE_CLASS_SUCCESS = typeof CREATE_CLASS_SUCCESS
export const CREATE_CLASS_FAILED = 'CREATE_CLASS_FAILED'
export type CREATE_CLASS_FAILED = typeof CREATE_CLASS_FAILED
export const CREATE_CLASS_UNSUCCESS = 'CREATE_CLASS_UNSUCCESS'
export type CREATE_CLASS_UNSUCCESS = typeof CREATE_CLASS_UNSUCCESS
